# .render.yaml
services:
  - type: web
    name: telegram-shop-bot
    env: python
    pythonVersion: 3.10.14   # Примусова версія Python
    region: oregon           # Можеш змінити на свій регіон
    branch: main
    repo: https://github.com/VetalMT/telegram-shop-bot
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true         # Автоматичний деплой після пуша
    envVars:
      - key: BOT_TOKEN
        fromSecret: BOT_TOKEN
      - key: ADMIN_ID
        fromSecret: ADMIN_ID
      - key: DB_HOST
        fromSecret: DB_HOST
      - key: DB_NAME
        fromSecret: DB_NAME
      - key: DB_USER
        fromSecret: DB_USER
      - key: DB_PASSWORD
        fromSecret: DB_PASSWORD
      - key: RENDER_EXTERNAL_URL
        value: https://telegram-shop-bot-z03b.onrender.com
      - key: PORT
        value: 10000
