services:
  - type: web
    name: telegram-shop-bot
    env: python
    pythonVersion: "3.10.14"
    plan: free
    region: oregon
    repo: https://github.com/VetalMT/telegram-shop-bot
    branch: main
    buildCommand: "pip install --upgrade pip && pip install -r requirements.txt"
    startCommand: "python app.py"
    autoDeploy: true