# Використовуємо офіційний Python
FROM python:3.11-slim

# Встановлюємо залежності системи
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо requirements
COPY requirements.txt .

# Встановлюємо Python-залежності
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо увесь код
COPY . .

# Запуск
CMD ["python", "app.py"]
